@startmindmap
* 53 🔹
** 22 🔹
*** 11 t
*** 11 🔹
**** 5 🔹
***** 2 c
***** 3 n
**** 6 🔹
***** 3  
***** 3 🔹
****** 1 .
****** 2 e
** 31 🔹
*** 15 🔹
**** 7 a
**** 8 🔹
***** 4 s
***** 4 🔹
****** 2 T
****** 2 i
*** 16 🔹
**** 8 🔹
***** 4 🔹
****** 2 S
****** 2 p
***** 4 🔹
****** 2 🔹
******* 1 ;
******* 1 )
****** 2 d
**** 8 🔹
***** 4 🔹
****** 2 y
****** 2 🔹
******* 1 (
******* 1 M
***** 4 🔹
****** 2 r
****** 2 k
@endmindmap
