@startmindmap
* 39
** 18
*** 9
**** 5
***** 3
****** 1
******* 2
****** 4
***** 7
****** 6
****** 8
**** 13
***** 11
****** 10
****** 12
***** 15
****** 14
****** 16
******* 17
*** 24
**** 22
***** 20
****** 19
****** 21
***** 23
**** 28
***** 26
****** 25
****** 27
***** 30
****** 29
** 56
*** 48
**** 42
***** 40
****** 41
***** 45
**** 50
***** 49
***** 55
*** 87
**** 81
***** 77
****** 66
***** 83
****** 82
****** 86
**** 99
***** 88
@endmindmap
